import fs from 'node:fs';
import { chapters, exercises, sources, coverageAudit } from './src/data.mjs';
const html=fs.readFileSync('./index.html','utf8');
const app=fs.readFileSync('./src/app.mjs','utf8');
const hero=fs.readFileSync('./src/hero.mjs','utf8');
const css=fs.readFileSync('./styles.css','utf8');
const single=fs.readFileSync('./CP2K_Academy_VASP_Migration.html','utf8');
const checks=[];
const ck=(name,ok)=>{checks.push([name,!!ok]); if(!ok) process.exitCode=1;};
ck('30 chapters',chapters.length===30);
ck('>=180 exercises',exercises.length>=180);
ck('>=6 exercises every chapter',chapters.every(c=>exercises.filter(e=>e.chapterId===c.id).length>=6));
ck('answers always exist',exercises.every(e=>e.answers?.[0]&&e.explanation&&e.hint));
ck('all source ids resolve',exercises.every(e=>!e.sourceId||sources[e.sourceId]));
ck('all source urls https',Object.values(sources).every(s=>/^https:\/\//.test(s.url)));
ck('2026.2 DFT+U kpoint correction present',JSON.stringify(chapters).includes('2026.2')&&JSON.stringify(chapters).includes('Mulliken'));
ck('outdated blanket DFT+U no-kpoint claim absent',!JSON.stringify(chapters).includes('DFT+U 尚未实现一般 k-points 支持'));
ck('always-visible answer button',html.includes('id="answerBtn"')&&app.includes('showAnswer'));
ck('BINGO and WRONG',app.includes('BINGO ✓')&&app.includes('WRONG ×'));
ck('auto next ~820ms',app.includes('setTimeout(()=>pickQuestion(),820)'));
ck('random refresh',app.includes("refresh.addEventListener('click',()=>pickQuestion())"));
ck('localStorage progress',app.includes('localStorage'));
ck('particle CP2K and ACADEMY',hero.includes("fillText('CP2K'")&&hero.includes("fillText('ACADEMY'"));
ck('pointer ripple physics',hero.includes('pointermove')&&hero.includes('ripple')&&hero.includes('requestAnimationFrame'));
ck('hero scroll fade/reveal',css.includes('.hero.scrolled')&&css.includes('.workspace.visible'));
ck('glassmorphism',css.includes('backdrop-filter:blur'));
ck('black-gold palette',css.includes('--gold:#d5b36a')&&css.includes('--bg:#050505'));
ck('reduced motion',css.includes('prefers-reduced-motion')&&hero.includes('prefers-reduced-motion'));
ck('single HTML built',single.includes('<style>')&&single.includes('CP2K Academy')&&single.includes('showAnswer'));
ck('honest scope boundary',/不声称|不宣称/.test(coverageAudit.scopeBoundary));
for(const [n,ok] of checks) console.log(`${ok?'PASS':'FAIL'}  ${n}`);
console.log(`\n${checks.filter(x=>x[1]).length}/${checks.length} audit checks passed`);
